# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dopNN Net - CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9 Preview
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      working-directory: Tests/
      run: dotnet test --no-build --verbosity normal
      # run: |
      #   for proj in Tests/**/*.csproj; do
      #     dotnet test "$proj" --no-build --verbosity normal
      #   done
